version: '3'
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    env_file:
      - .env.local
    volumes:
      - ./:/usr/local/apps/myapp
      - /usr/local/apps/myapp/node_modules

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: cinematography
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
volumes:
  ignore: