import { MigrationInterface, QueryRunner } from 'typeorm';
import { Actor } from '../features/actor/actor.entity';
import { Director } from '../features/director/director.entity';
import { Movie } from '../features/movies/movie.entity';
import { TvShow } from '../features/shows/tv.shows/tv.show.entity';
import { TvShowSeason } from '../features/shows/seasons/tv.show.season.entity';
import { TvShowEpisode } from '../features/shows/episodes/tv.show.episode.entity';

export class InitialData1687083928778 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const actors: Actor[] = [
      {
        id: 1,
        birthDate: '1970-01-01',
        name: 'Tom Hanks',
        nationality: 'American',
      },
      {
        id: 2,
        birthDate: '1967-09-25',
        name: 'Catherine Zeta-Jones',
        nationality: 'Welsh',
      },
      {
        id: 3,
        birthDate: '1980-11-11',
        name: 'Ryan Reynolds',
        nationality: 'Canadian',
      },
    ];

    const directors: Partial<Director>[] = [
      {
        id: 1,
        birthDate: '1956-07-09',
        name: 'Steven Spielberg',
        nationality: 'American',
      },
      {
        id: 2,
        birthDate: '1960-10-28',
        name: 'Robert Zemeckis',
        nationality: 'American',
      },
    ];

    const movies: Partial<Movie>[] = [
      {
        title: 'Movie 1',
        description: 'Description of Movie 1',
        year: 2022,
        duration: 120,
        genre: 'Action',
        rating: 7.5,
        director: {
          birthDate: '1956-07-09',
          name: 'Steven Spielberg',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
          id: 1,
        },
        actors: [
          {
            id: 1,
            birthDate: '1970-01-01',
            name: 'Tom Hanks',
            nationality: 'American',
          },
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
        ],
      },
      {
        title: 'Movie 2',
        description: 'Description of Movie 2',
        year: 2023,
        duration: 110,
        genre: 'Comedy',
        rating: 6.8,
        director: {
          id: 2,
          birthDate: '1960-10-28',
          name: 'Robert Zemeckis',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
          {
            id: 3,
            birthDate: '1980-11-11',
            name: 'Ryan Reynolds',
            nationality: 'Canadian',
          },
        ],
      },
    ];

    const tvShows: Partial<TvShow>[] = [
      {
        id: 1,
        title: 'TV Show 1',
        description: 'Description of TV Show 1',
        seasonsQ: 3,
        genre: 'Action',
        beginYear: 2020,
        endYear: 2023,
        rating: 8.2,
        seasons: [],
      },
      {
        id: 2,
        title: 'TV Show 2',
        description: 'Description of TV Show 2',
        seasonsQ: 5,
        genre: 'Drama',
        beginYear: 2018,
        endYear: 2021,
        rating: 9.1,
        seasons: [],
      },
    ];

    const tvShowSeasons: Partial<TvShowSeason>[] = [
      {
        id: 1,
        title: 'Season 1',
        description: 'Description of Season 1',
        year: 2020,
        seasonNumber: 1,
        episodesQ: 10,
        rating: 8.5,
        tvShow: {
          id: 1,
          title: 'TV Show 1',
          description: 'Description of TV Show 1',
          seasonsQ: 3,
          genre: 'Action',
          beginYear: 2020,
          endYear: 2023,
          rating: 8.2,
          seasons: [],
        },
        episodes: [],
      },
      {
        id: 2,
        title: 'Season 2',
        description: 'Description of Season 2',
        year: 2021,
        seasonNumber: 2,
        episodesQ: 12,
        rating: 9.0,
        tvShow: {
          id: 1,
          title: 'TV Show 1',
          description: 'Description of TV Show 1',
          seasonsQ: 3,
          genre: 'Action',
          beginYear: 2020,
          endYear: 2023,
          rating: 8.2,
          seasons: [],
        },
        episodes: [],
      },
      // Agrega más registros según sea necesario
    ];

    const episodes: Partial<TvShowEpisode>[] = [
      {
        id: 1,
        title: 'Episode 1',
        description: 'Description of Episode 1',
        episode_number: 1,
        year: 2022,
        duration: 40,
        rating: 8.5,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2020,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.5,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Action',
            beginYear: 2020,
            endYear: 2023,
            rating: 8.2,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 1,
          birthDate: '1956-07-09',
          name: 'Steven Spielberg',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 1,
            birthDate: '1970-01-01',
            name: 'Tom Hanks',
            nationality: 'American',
          },
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
        ],
      },
      {
        id: 2,
        title: 'Episode 2',
        description: 'Description of Episode 2',
        episode_number: 2,
        year: 2022,
        duration: 45,
        rating: 8.8,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2021,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 2,
          birthDate: '1960-10-28',
          name: 'Robert Zemeckis',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
          {
            id: 3,
            birthDate: '1980-11-11',
            name: 'Ryan Reynolds',
            nationality: 'Canadian',
          },
        ],
      },
      {
        id: 3,
        title: 'Episode 3',
        description: 'Description of Episode 3',
        episode_number: 3,
        year: 2022,
        duration: 42,
        rating: 9.1,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2021,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 1,
          birthDate: '1956-07-09',
          name: 'Steven Spielberg',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 3,
            birthDate: '1980-11-11',
            name: 'Ryan Reynolds',
            nationality: 'Canadian',
          },
        ],
      },
      {
        id: 4,
        title: 'Episode 4',
        description: 'Description of Episode 4',
        episode_number: 4,
        year: 2022,
        duration: 38,
        rating: 8.7,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2021,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 2,
          birthDate: '1960-10-28',
          name: 'Robert Zemeckis',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
          {
            id: 3,
            birthDate: '1980-11-11',
            name: 'Ryan Reynolds',
            nationality: 'Canadian',
          },
        ],
      },
      {
        id: 5,
        title: 'Episode 5',
        description: 'Description of Episode 5',
        episode_number: 5,
        year: 2022,
        duration: 39,
        rating: 8.6,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2022,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 1,
          birthDate: '1956-07-09',
          name: 'Steven Spielberg',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 1,
            birthDate: '1970-01-01',
            name: 'Tom Hanks',
            nationality: 'American',
          },
        ],
      },
      {
        id: 6,
        title: 'Episode 6',
        description: 'Description of Episode 6',
        episode_number: 6,
        year: 2022,
        duration: 43,
        rating: 8.9,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2023,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 2,
          birthDate: '1960-10-28',
          name: 'Robert Zemeckis',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 1,
            birthDate: '1970-01-01',
            name: 'Tom Hanks',
            nationality: 'American',
          },
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
          {
            id: 3,
            birthDate: '1980-11-11',
            name: 'Ryan Reynolds',
            nationality: 'Canadian',
          },
        ],
      },
      {
        id: 7,
        title: 'Episode 7',
        description: 'Description of Episode 7',
        episode_number: 7,
        year: 2022,
        duration: 41,
        rating: 8.7,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2023,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 1,
          birthDate: '1956-07-09',
          name: 'Steven Spielberg',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 1,
            birthDate: '1970-01-01',
            name: 'Tom Hanks',
            nationality: 'American',
          },
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
        ],
      },
      {
        id: 8,
        title: 'Episode 8',
        description: 'Description of Episode 8',
        episode_number: 8,
        year: 2022,
        duration: 44,
        rating: 8.8,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2022,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 2,
          birthDate: '1960-10-28',
          name: 'Robert Zemeckis',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 3,
            birthDate: '1980-11-11',
            name: 'Ryan Reynolds',
            nationality: 'Canadian',
          },
        ],
      },
      {
        id: 9,
        title: 'Episode 9',
        description: 'Description of Episode 9',
        episode_number: 9,
        year: 2022,
        duration: 37,
        rating: 8.5,
        season: {
          id: 1,
          title: 'Season 1',
          description: 'Description of Season 1',
          year: 2022,
          seasonNumber: 1,
          episodesQ: 10,
          rating: 8.3,
          tvShow: {
            id: 1,
            title: 'TV Show 1',
            description: 'Description of TV Show 1',
            seasonsQ: 3,
            genre: 'Drama',
            beginYear: 2021,
            endYear: 2021,
            rating: 8.7,
            seasons: [],
          },
          episodes: [],
        },
        director: {
          id: 1,
          birthDate: '1956-07-09',
          name: 'Steven Spielberg',
          nationality: 'American',
          movies: [],
          tvShowsEpisodes: [],
        },
        actors: [
          {
            id: 2,
            birthDate: '1967-09-25',
            name: 'Catherine Zeta-Jones',
            nationality: 'Welsh',
          },
          {
            id: 3,
            birthDate: '1980-11-11',
            name: 'Ryan Reynolds',
            nationality: 'Canadian',
          },
        ],
      },
    ];

    await queryRunner.manager.getRepository(Actor).save(actors);
    await queryRunner.manager.getRepository(Director).save(directors);
    await queryRunner.manager.getRepository(TvShow).save(tvShows);
    await queryRunner.manager.getRepository(TvShowSeason).save(tvShowSeasons);
    await queryRunner.manager.getRepository(TvShowEpisode).save(episodes);
    await queryRunner.manager.getRepository(Movie).save(movies);
  }
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.manager.getRepository(TvShowEpisode).delete({});
    await queryRunner.manager.getRepository(TvShowSeason).delete({});
    await queryRunner.manager.getRepository(TvShow).delete({});
    await queryRunner.manager.getRepository(Movie).delete({});
    await queryRunner.manager.getRepository(Actor).delete({});
    await queryRunner.manager.getRepository(Director).delete({});
  }
}
